### ISSUE TITLE
[Feature request] Add Gravatar to Staticman comments

### ISSUE THREAD

**Issue by VincentTam** [robinmetral/eaudepoisson#38]
Many blog theme with Staticman integration uses Gravatar, say Minimal Mistakes, Beautiful Jekyll/Hugo, [Hugo Swith Theme](https://staticman-gitlab-pages.frama.io/hugo-swift-theme/post/hugoisforlovers/), etc.

**Comment by robinmetral** [comment]
We were initially thinking of not saving commenter emails (we want to respect their privacy and, honestly, we wouldn't really need their emails). Without emails I don't think we could implement Gravatar.

Were you suggesting Gravatar because of the more personal feeling it gives a comment thread? Maybe there are other solutions to solve this issue.

Everything is still open to discussion of course! :slightly_smiling_face:

**Comment by robinmetral** [comment]
Also @VincentTam, as you've seen it's been a while this project hasn't been worked on. Thanks a lot for opening #36, #37 and #38 - a good reminder that I should get back to it!

First things first, there are a few things I need to update, starting with the README and legacy issues that aren't relevant anymore. Thanks for bearing with me in the meantime, and thank you for your contributions!

**Comment by VincentTam** [comment]
> We were initially thinking of not saving commenter emails (we want to respect their privacy and, honestly, we wouldn't really need their emails). Without emails I don't think we could implement Gravatar.

Oh!  There's no field `email` in `staticman.yml`.  If I had seen that at the first place, I wouldn't have opened this issue.  IMO, unless you've a Mailgun account associated with the API instance, the `email` is just for display.  I personally prefer having Gravatar for visual reasons, without researching deep about the Gravatar service.  However, it's optional: it's totally fine without Gravatar.

I'm following a one-problem-one-issue mindset, so I open separate issues for separate things.

**Comment by robinmetral** [comment]
> Oh! There's no field `email` in `staticman.yml`. If I had seen that at the first place, I wouldn't have opened this issue. IMO, unless you've a Mailgun account associated with the API instance, the `email` is just for display. I personally prefer having Gravatar for visual reasons, without researching deep about the Gravatar service. However, it's optional: it's totally fine without Gravatar.

Yep, Mailgun would be another thing to consider if we want to enable comment reply notifications. I'll open a new issue to discuss this in the future!

> I'm following a one-problem-one-issue mindset, so I open separate issues for separate things.

:+1: :slightly_smiling_face:
